server:
  servlet:
    context-path: /

spring:
  application:
    name: dating-ai-server
  profiles:
    active: dev

# 提示词模板配置
dating:
  ai:
    prompt:
      template-path: classpath:/prompts/system/
      templates:
        - consolidated-response
        - consolidated-analysis
        - rag-context
    chat:
      ai:
        max-tokens: 300
        temperature: 0.7
        emotion-factor-weights:
          sentiment: 0.4
          syntax: 0.2
          response-time: 0.15
          coherence: 0.15
          symbol: 0.1
        max-topic-turns: 3
        emotion-drop-threshold: 15.0

# JWT配置
jwt:
  secret: ${JWT_SECRET:datingAiSecretKey}
  expire-seconds: 86400

# Knife4j API文档配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
    enable-swagger-models: true
    enable-filter-multipart-apis: false
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-footer: false
    enable-footer-custom: false
    enable-home-custom: false
    enable-debug: true 